name: Test
on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: npm run lint:prettier

  test:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: npm run test

  test-type:
    name: Type checking
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: npm run test:type

  test-example-app:
    name: Test example app
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: |
          cd ./examples/publicodes-react
          npm ci
          npm test

  test-packages-versioning:
    name: Enforce consistent package versioning
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npx zx ./.github/scripts/enforce-versions.mjs
