name: Test and Publish
on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: yarn lint:prettier

  test:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: yarn test

  test-type:
    name: Type checking
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: yarn test:type

  test-example-app:
    name: Test example app
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: |
          cd ./examples/publicodes-react
          yarn install
          yarn test

  # This job could be in a separate workflow triggered when all the tests passes
  # using the `workflow_run` event, but it makes it difficult to retrieve the
  # commit message.
  publish:
    if: contains(join(github.event.commits.*.message, ' | '), '📦 Publicodes v1.0.0-beta.') && github.ref == 'refs/heads/master'
    needs: [test, test-type, test-example-app]
    runs-on: ubuntu-20.04
    steps:
      - uses: ./.github/actions/install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_SECRET }}
          dry-run: ${{ github.ref != 'refs/heads/master' }}
          package: ./packages/core/package.json
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_SECRET }}
          dry-run: ${{ github.ref != 'refs/heads/master' }}
          package: ./packages/react-ui/package.json
